const PDFDocument = require('pdfkit');

// Helper to generate a PDF in memory and return as base64 string
function generatePDFBase64(missingPerson, foundPerson, matchDetails) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40 });
      const buffers = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        const base64 = pdfData.toString('base64');
        resolve(`data:application/pdf;base64,${base64}`);
      });

      // --- HEADER ---
      doc.fontSize(24).fillColor('#d32f2f').text('FAMILYLINK-AI', { align: 'center' });
      doc.fontSize(10).fillColor('#666666').text('AUTOMATED INTELLIGENCE REUNIFICATION REPORT', { align: 'center' });
      doc.moveDown(1);

      doc.rect(40, doc.y, 515, 30).fill('#f5f5f5');
      doc.fillColor('#d32f2f').fontSize(9).text('DISCLAIMER: This report is auto-generated by FAMILYLINK-AI. AI recommendations require human verification.', 50, doc.y + 10, { width: 500, align: 'center' });
      doc.moveDown(3);

      // --- EVENT SUMMARY ---
      doc.rect(40, doc.y, 515, 20).fill('#e0e0e0');
      doc.fillColor('#000000').fontSize(12).font('Helvetica-Bold').text('EVENT SUMMARY', 50, doc.y + 5);
      doc.moveDown(1.5);
      
      const summaryY = doc.y;
      doc.font('Helvetica-Bold').fontSize(10).text('Case ID:', 50, summaryY);
      doc.font('Helvetica').text(missingPerson.id, 150, summaryY);
      doc.font('Helvetica-Bold').text('Status:', 50, summaryY + 15);
      doc.fillColor('green').text('VERIFIED MATCH FOUND', 150, summaryY + 15);
      doc.fillColor('#000').font('Helvetica-Bold').text('Match Confidence:', 50, summaryY + 30);
      doc.font('Helvetica').text(`${matchDetails.total_score}%`, 150, summaryY + 30);
      doc.moveDown(3);

      // --- MISSING PERSON DATA ---
      doc.rect(40, doc.y, 515, 20).fill('#e0e0e0');
      doc.fillColor('#000000').fontSize(12).font('Helvetica-Bold').text('REPORTED MISSING PERSON DATA', 50, doc.y + 5);
      doc.moveDown(1.5);

      const mY = doc.y;
      doc.font('Helvetica-Bold').fontSize(10).text('Name:', 50, mY);
      doc.font('Helvetica').text(missingPerson.person_name, 150, mY);
      doc.font('Helvetica-Bold').text('Age & Gender:', 50, mY + 15);
      doc.font('Helvetica').text(`${missingPerson.age || 'Unknown'} | ${missingPerson.gender || 'Unknown'}`, 150, mY + 15);
      doc.font('Helvetica-Bold').text('Last Location:', 50, mY + 30);
      doc.font('Helvetica').text(missingPerson.last_seen_loc || 'N/A', 150, mY + 30);
      doc.font('Helvetica-Bold').text('Physical Desc:', 50, mY + 45);
      doc.font('Helvetica').text(missingPerson.physical_desc || 'N/A', 150, mY + 45, { width: 380 });
      doc.moveDown(3);

      // --- FOUND PERSON DATA ---
      doc.rect(40, doc.y, 515, 20).fill('#e0e0e0');
      doc.fillColor('#000000').fontSize(12).font('Helvetica-Bold').text('FOUND PERSON DATA (THE MATCH)', 50, doc.y + 5);
      doc.moveDown(1.5);

      const fY = doc.y;
      doc.font('Helvetica-Bold').fontSize(10).text('Found Record ID:', 50, fY);
      doc.font('Helvetica').text(foundPerson.id, 150, fY);
      doc.font('Helvetica-Bold').text('Name (if known):', 50, fY + 15);
      doc.font('Helvetica').text(foundPerson.name_if_known || 'Unknown', 150, fY + 15);
      doc.font('Helvetica-Bold').text('Location Found:', 50, fY + 30);
      doc.font('Helvetica').text(foundPerson.location_name || 'N/A', 150, fY + 30);
      doc.font('Helvetica-Bold').text('Facility / Camp:', 50, fY + 45);
      doc.font('Helvetica').text(foundPerson.org_name || 'N/A', 150, fY + 45);
      doc.font('Helvetica-Bold').text('Physical Desc:', 50, fY + 60);
      doc.font('Helvetica').text(foundPerson.physical_desc || 'N/A', 150, fY + 60, { width: 380 });
      doc.moveDown(3);

      // --- AI MATCH DIAGNOSTICS ---
      doc.rect(40, doc.y, 515, 20).fill('#e0e0e0');
      doc.fillColor('#000000').fontSize(12).font('Helvetica-Bold').text('AI MATCH DIAGNOSTICS', 50, doc.y + 5);
      doc.moveDown(1.5);
      
      const scores = `Name: ${matchDetails.name_score}%  |  Age: ${matchDetails.age_score}%  |  Gender: ${matchDetails.gender_score}%  |  Location: ${matchDetails.location_score}%  |  Desc: ${matchDetails.desc_score}%`;
      doc.font('Helvetica').fontSize(10).text(scores, 50, doc.y, { align: 'center', width: 500 });
      doc.moveDown(3);

      // --- ACTION REQUIRED ---
      doc.rect(40, doc.y, 515, 40).fill('#e8f5e9');
      doc.fillColor('#2e7d32').font('Helvetica-Bold').fontSize(12).text('ACTION REQUIRED', 50, doc.y + 10, { align: 'center', width: 500 });
      doc.fillColor('#000').font('Helvetica').fontSize(10).text(`Please contact the relief camp at ${foundPerson.location_name || foundPerson.org_name || 'the local district'} immediately to coordinate reunification.`, 50, doc.y + 5, { align: 'center', width: 500 });
      
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

// Notifications System using EmailJS HTTP API
async function sendReunificationAlert(caseData) {
  const { caseId, reporterEmail, missingPerson, foundPerson, matchDetails } = caseData;

  console.log(`[NOTIFY] Initiating EmailJS notification for Case ${caseId}`);

  if (reporterEmail && reporterEmail.includes('@')) {
    try {
      console.log(`[NOTIFY] Generating PDF report and sending to ${reporterEmail}...`);
      
      const pdfDataUri = await generatePDFBase64(missingPerson, foundPerson, matchDetails);

      const payload = {
        service_id: process.env.EMAILJS_SERVICE_ID,
        template_id: process.env.EMAILJS_TEMPLATE_ID,
        user_id: process.env.EMAILJS_PUBLIC_KEY,
        template_params: {
          to_email: reporterEmail,
          person_name: missingPerson.person_name,
          case_id: caseId,
          content: 'Please find the attached PDF report regarding the verified match for your reported missing person. Contact the relief camp authorities immediately as indicated in the report.',
          // The attachment data string is automatically handled by EmailJS if the template is configured to accept it
          attachment: pdfDataUri
        }
      };

      const response = await fetch('https://api.emailjs.com/api/v1.0/email/send', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (response.ok) {
        console.log('[NOTIFY] PDF Report Email sent successfully via EmailJS!');
      } else {
        const text = await response.text();
        console.error('[NOTIFY Error] EmailJS failed:', text);
      }
    } catch (err) {
      console.error('[NOTIFY Error] EmailJS network request failed:', err.message);
    }
  } else {
    console.log('[NOTIFY] No valid email provided. Skipping.');
  }
}

module.exports = { sendReunificationAlert };
