// Notifications System using EmailJS HTTP API (Bypasses Render SMTP Block)

async function sendReunificationAlert(caseData) {
  const { caseId, reporterEmail, missingPerson, foundPerson, matchDetails } = caseData;

  console.log(`[NOTIFY] Initiating EmailJS notification for Case ${caseId}`);

  if (reporterEmail && reporterEmail.includes('@')) {
    try {
      console.log(`[NOTIFY] Sending live HTML Report to ${reporterEmail} via EmailJS...`);
      
      const htmlReport = `
        <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; color: #333;">
          <h1 style="color: #d32f2f; border-bottom: 2px solid #d32f2f; padding-bottom: 10px; margin-bottom: 0;">FAMILYLINK-AI</h1>
          <p style="font-size: 12px; color: #666; margin-top: 5px;">AUTOMATED INTELLIGENCE REUNIFICATION REPORT</p>
          <p style="font-size: 11px; font-style: italic; background: #f5f5f5; padding: 10px; border-left: 3px solid #d32f2f;">
            DISCLAIMER: This report is auto-generated by FAMILYLINK-AI. AI recommendations require human verification. This document serves as official notification of a verified match.
          </p>

          <h2 style="background: #e0e0e0; padding: 8px; font-size: 14px; text-transform: uppercase;">Event Summary</h2>
          <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
            <tr><td style="width: 30%; padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Case ID</td><td style="padding: 6px; border-bottom: 1px solid #eee;">${missingPerson.id}</td></tr>
            <tr><td style="padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Status</td><td style="padding: 6px; border-bottom: 1px solid #eee; color: green; font-weight: bold;">VERIFIED MATCH FOUND</td></tr>
            <tr><td style="padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Match Confidence</td><td style="padding: 6px; border-bottom: 1px solid #eee;">${matchDetails.total_score}%</td></tr>
            <tr><td style="padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Verified By</td><td style="padding: 6px; border-bottom: 1px solid #eee;">${matchDetails.verified_by || 'Authorized Officer'}</td></tr>
          </table>

          <h2 style="background: #e0e0e0; padding: 8px; font-size: 14px; text-transform: uppercase; margin-top: 20px;">Reported Missing Person Data</h2>
          <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
            <tr style="background: #f9f9f9;"><td style="width: 30%; padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Name</td><td style="padding: 6px; border-bottom: 1px solid #eee;">${missingPerson.person_name}</td></tr>
            <tr><td style="padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Age & Gender</td><td style="padding: 6px; border-bottom: 1px solid #eee;">${missingPerson.age || 'Unknown'} | ${missingPerson.gender || 'Unknown'}</td></tr>
            <tr style="background: #f9f9f9;"><td style="padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Last Seen Location</td><td style="padding: 6px; border-bottom: 1px solid #eee;">${missingPerson.last_seen_loc || 'N/A'}</td></tr>
            <tr><td style="padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Physical Desc</td><td style="padding: 6px; border-bottom: 1px solid #eee;">${missingPerson.physical_desc || 'N/A'}</td></tr>
            <tr style="background: #f9f9f9;"><td style="padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Medical Info</td><td style="padding: 6px; border-bottom: 1px solid #eee;">${missingPerson.medical_info || 'N/A'}</td></tr>
          </table>

          <h2 style="background: #e0e0e0; padding: 8px; font-size: 14px; text-transform: uppercase; margin-top: 20px;">Found Person Data (The Match)</h2>
          <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
            <tr style="background: #f9f9f9;"><td style="width: 30%; padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Found Record ID</td><td style="padding: 6px; border-bottom: 1px solid #eee;">${foundPerson.id}</td></tr>
            <tr><td style="padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Name (if known)</td><td style="padding: 6px; border-bottom: 1px solid #eee;">${foundPerson.name_if_known || 'Unknown'}</td></tr>
            <tr style="background: #f9f9f9;"><td style="padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Location Found</td><td style="padding: 6px; border-bottom: 1px solid #eee;">${foundPerson.location_name || 'N/A'}</td></tr>
            <tr><td style="padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Facility / Camp</td><td style="padding: 6px; border-bottom: 1px solid #eee;">${foundPerson.org_name || 'N/A'}</td></tr>
            <tr style="background: #f9f9f9;"><td style="padding: 6px; font-weight: bold; border-bottom: 1px solid #eee;">Physical Desc</td><td style="padding: 6px; border-bottom: 1px solid #eee;">${foundPerson.physical_desc || 'N/A'}</td></tr>
          </table>

          <h2 style="background: #e0e0e0; padding: 8px; font-size: 14px; text-transform: uppercase; margin-top: 20px;">AI Match Diagnostics</h2>
          <table style="width: 100%; border-collapse: collapse; font-size: 13px; text-align: center;">
            <tr style="background: #f5f5f5; font-weight: bold; border-bottom: 2px solid #ccc;">
              <td style="padding: 6px;">Name Score</td>
              <td style="padding: 6px;">Age Score</td>
              <td style="padding: 6px;">Gender Score</td>
              <td style="padding: 6px;">Location Score</td>
              <td style="padding: 6px;">Desc Score</td>
            </tr>
            <tr>
              <td style="padding: 6px;">${matchDetails.name_score}%</td>
              <td style="padding: 6px;">${matchDetails.age_score}%</td>
              <td style="padding: 6px;">${matchDetails.gender_score}%</td>
              <td style="padding: 6px;">${matchDetails.location_score}%</td>
              <td style="padding: 6px;">${matchDetails.desc_score}%</td>
            </tr>
          </table>

          <div style="margin-top: 30px; padding: 15px; border: 2px solid #4CAF50; background: #e8f5e9; text-align: center;">
            <h3 style="color: #2E7D32; margin-top: 0;">ACTION REQUIRED</h3>
            <p style="margin-bottom: 0;">Please log into the FAMILYLINK-AI portal immediately or contact the relief camp at <strong>${foundPerson.location_name || foundPerson.org_name || 'the local district'}</strong> to coordinate reunification.</p>
          </div>
        </div>
      `;
      
      const payload = {
        service_id: process.env.EMAILJS_SERVICE_ID,
        template_id: process.env.EMAILJS_TEMPLATE_ID,
        user_id: process.env.EMAILJS_PUBLIC_KEY,
        template_params: {
          to_email: reporterEmail,
          html_content: htmlReport
        }
      };

      const response = await fetch('https://api.emailjs.com/api/v1.0/email/send', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (response.ok) {
        console.log('[NOTIFY] Comprehensive Report Email sent successfully via EmailJS!');
      } else {
        const text = await response.text();
        console.error('[NOTIFY Error] EmailJS failed:', text);
      }
    } catch (err) {
      console.error('[NOTIFY Error] EmailJS network request failed:', err.message);
    }
  } else {
    console.log('[NOTIFY] No valid email provided. Skipping.');
  }
}

module.exports = { sendReunificationAlert };
